### ISSUE TITLE
駒の弾く強さが調整できない

### ISSUE THREAD

**Issue by Efim123** [Efim123/SoredemosyogiwohazikitaiNEO#2]
駒の弾く強さを調節するためint power =10にして
カーソルのクリックした地点とクリックを離した地点の距離distanceをとりPlayerScriptの62行目で
tobasikoma.GetComponent<Rigidbody> ().AddForce (direction.normalized  * distance * power);
で駒を飛ばしそうとしたところ飛びすぎてしまいました。

不思議に思い
tobasikoma.GetComponent<Rigidbody> ().AddForce (direction.normalized  * distance );
にしてもあまり飛ばずpower = 0にして
tobasikoma.GetComponent<Rigidbody> ().AddForce (direction.normalized  * power );
をしても駒が飛んでしまいました。
同じ変数なのに飛びの勢いがこうも違うのは何故でしょうか?

またQiita記事に関連してIssueでスクリプト文をどのように書けばいいでしょうか？

**Comment by Ayarin226** [comment]
publicな変数を用意すると，そのスクリプトを何かに貼り付けた時点でインスペクターで値をいじることが可能になります．このことを，シリアライズされると言います．
そのため，変数の宣言での値の代入は一度スクリプトをアタッチした後からは実行しても意味がないです．

今回であれば，インスペクターでpowerの値に 1000 を代入しているため，その値で `AddForce` されて行きます．

publicな変数を使った時にはInspectorを常に見るようにするといいと思います．

![2018-05-05 12 27 28](https://user-images.githubusercontent.com/38731389/39659288-18d5a61c-5060-11e8-9d49-ac0dcf4a7f7e.png)

また，スクリプトをMarkdownの文章中に記載するには， \` (バッククォート)で単語を挟む `このようになります` か， ``` (バッククォートを三つ)で挟むと
```
このようになる
```
のでコードを書く際にはこの二つを使用すると見やすい記載が可能になると思います！
