### ISSUE TITLE
Rigidbodyの追加/削除

### ISSUE THREAD

**Issue by Efim123** [Efim123/SoredemosyogiwohazikitaiNEO#3]
他の駒にくっついている駒を弾きやすくするため、
くっつかれた駒のRigidBodyの削除/追加を行おうとしているのですが
RigidBodyの追加がうまくいきません。

Koma1Script/ Koma2Scriptの最後の方にあるOnrigidメソッドで駒の追加を行おうとしており
メソッドのDeBugに関しては確認済みです。

またNonrigidメソッドで

```Rigidbody rigid = (Rigidbody)this.GetComponent<Rigidbody>();```
```GameObject.DestroyImmediate(rigid);```

でRigidBodyを削除できていますが
Rigidbodyそのもののを消すのではなく機能を停止/再開することは可能でしょうか？

**Comment by Ayarin226** [comment]
弾くのにRigidbodyのどの機能が邪魔なのかな？
